// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _SM3Calc_HH_
#define _SM3Calc_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "processmessageblock.h"
#include "SM3Calc_messageBldEe.h"
#include "SM3Calc_intermedieOg.h"

namespace ap_rtl {

struct SM3Calc : public sc_module {
    // Port declarations 14
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<5> > message_address0;
    sc_out< sc_logic > message_ce0;
    sc_in< sc_lv<8> > message_q0;
    sc_in< sc_lv<8> > messageLen;
    sc_out< sc_lv<3> > digest_address0;
    sc_out< sc_logic > digest_ce0;
    sc_out< sc_logic > digest_we0;
    sc_out< sc_lv<32> > digest_d0;


    // Module declarations
    SM3Calc(sc_module_name name);
    SC_HAS_PROCESS(SM3Calc);

    ~SM3Calc();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    SM3Calc_messageBldEe* messageBlock_U;
    SM3Calc_intermedieOg* intermediateHash_U;
    processmessageblock* grp_processmessageblock_fu_297;
    sc_signal< sc_lv<11> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<6> > i_fu_309_p2;
    sc_signal< sc_lv<6> > i_reg_700;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > icmp_ln210_fu_303_p2;
    sc_signal< sc_lv<5> > trunc_ln212_fu_320_p1;
    sc_signal< sc_lv<5> > trunc_ln212_reg_710;
    sc_signal< sc_lv<512> > p_Result_3_fu_366_p5;
    sc_signal< sc_lv<512> > p_Result_3_reg_715;
    sc_signal< sc_lv<512> > p_Result_1_fu_516_p2;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<5> > i_6_fu_528_p2;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<4> > i_7_fu_664_p2;
    sc_signal< sc_lv<4> > i_7_reg_737;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_lv<1> > icmp_ln236_fu_658_p2;
    sc_signal< sc_lv<4> > messageBlock_address0;
    sc_signal< sc_logic > messageBlock_ce0;
    sc_signal< sc_logic > messageBlock_we0;
    sc_signal< sc_lv<32> > messageBlock_d0;
    sc_signal< sc_lv<32> > messageBlock_q0;
    sc_signal< sc_lv<3> > intermediateHash_address0;
    sc_signal< sc_logic > intermediateHash_ce0;
    sc_signal< sc_logic > intermediateHash_we0;
    sc_signal< sc_lv<32> > intermediateHash_d0;
    sc_signal< sc_lv<32> > intermediateHash_q0;
    sc_signal< sc_lv<3> > intermediateHash_address1;
    sc_signal< sc_logic > intermediateHash_ce1;
    sc_signal< sc_logic > intermediateHash_we1;
    sc_signal< sc_lv<32> > intermediateHash_d1;
    sc_signal< sc_lv<32> > intermediateHash_q1;
    sc_signal< sc_logic > grp_processmessageblock_fu_297_ap_start;
    sc_signal< sc_logic > grp_processmessageblock_fu_297_ap_done;
    sc_signal< sc_logic > grp_processmessageblock_fu_297_ap_idle;
    sc_signal< sc_logic > grp_processmessageblock_fu_297_ap_ready;
    sc_signal< sc_lv<3> > grp_processmessageblock_fu_297_intermediateHash_address0;
    sc_signal< sc_logic > grp_processmessageblock_fu_297_intermediateHash_ce0;
    sc_signal< sc_logic > grp_processmessageblock_fu_297_intermediateHash_we0;
    sc_signal< sc_lv<32> > grp_processmessageblock_fu_297_intermediateHash_d0;
    sc_signal< sc_lv<3> > grp_processmessageblock_fu_297_intermediateHash_address1;
    sc_signal< sc_logic > grp_processmessageblock_fu_297_intermediateHash_ce1;
    sc_signal< sc_logic > grp_processmessageblock_fu_297_intermediateHash_we1;
    sc_signal< sc_lv<32> > grp_processmessageblock_fu_297_intermediateHash_d1;
    sc_signal< sc_lv<4> > grp_processmessageblock_fu_297_messageBlock_address0;
    sc_signal< sc_logic > grp_processmessageblock_fu_297_messageBlock_ce0;
    sc_signal< sc_lv<512> > p_Val2_2_reg_251;
    sc_signal< sc_lv<6> > i_0_reg_263;
    sc_signal< sc_lv<5> > i_1_reg_274;
    sc_signal< sc_lv<1> > icmp_ln222_fu_522_p2;
    sc_signal< sc_lv<4> > i_3_reg_285;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_logic > grp_processmessageblock_fu_297_ap_start_reg;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_lv<64> > zext_ln212_fu_315_p1;
    sc_signal< sc_lv<64> > zext_ln224_1_fu_653_p1;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<64> > zext_ln238_fu_680_p1;
    sc_signal< sc_lv<64> > zext_ln238_1_fu_685_p1;
    sc_signal< sc_lv<10> > zext_ln216_2_fu_327_p1;
    sc_signal< sc_lv<10> > sub_ln216_fu_330_p2;
    sc_signal< sc_lv<512> > zext_ln216_1_fu_336_p1;
    sc_signal< sc_lv<9> > zext_ln216_fu_324_p1;
    sc_signal< sc_lv<9> > xor_ln218_fu_346_p2;
    sc_signal< sc_lv<512> > pack_fu_340_p2;
    sc_signal< sc_lv<32> > zext_ln218_fu_352_p1;
    sc_signal< sc_lv<512> > p_Result_2_fu_356_p4;
    sc_signal< sc_lv<8> > shl_ln_fu_377_p3;
    sc_signal< sc_lv<8> > or_ln212_fu_384_p2;
    sc_signal< sc_lv<10> > zext_ln212_1_fu_396_p1;
    sc_signal< sc_lv<1> > icmp_ln212_fu_390_p2;
    sc_signal< sc_lv<10> > zext_ln212_2_fu_400_p1;
    sc_signal< sc_lv<10> > xor_ln212_fu_408_p2;
    sc_signal< sc_lv<10> > select_ln212_fu_414_p3;
    sc_signal< sc_lv<10> > select_ln212_2_fu_430_p3;
    sc_signal< sc_lv<10> > select_ln212_1_fu_422_p3;
    sc_signal< sc_lv<10> > xor_ln212_1_fu_438_p2;
    sc_signal< sc_lv<512> > zext_ln212_3_fu_404_p1;
    sc_signal< sc_lv<512> > zext_ln212_4_fu_444_p1;
    sc_signal< sc_lv<512> > shl_ln212_fu_456_p2;
    sc_signal< sc_lv<512> > tmp_fu_462_p4;
    sc_signal< sc_lv<512> > zext_ln212_5_fu_448_p1;
    sc_signal< sc_lv<512> > zext_ln212_6_fu_452_p1;
    sc_signal< sc_lv<512> > shl_ln212_1_fu_480_p2;
    sc_signal< sc_lv<512> > lshr_ln212_fu_486_p2;
    sc_signal< sc_lv<512> > and_ln212_fu_492_p2;
    sc_signal< sc_lv<512> > xor_ln212_2_fu_498_p2;
    sc_signal< sc_lv<512> > select_ln212_3_fu_472_p3;
    sc_signal< sc_lv<512> > and_ln212_1_fu_504_p2;
    sc_signal< sc_lv<512> > and_ln212_2_fu_510_p2;
    sc_signal< sc_lv<4> > trunc_ln224_fu_534_p1;
    sc_signal< sc_lv<9> > shl_ln1_fu_538_p3;
    sc_signal< sc_lv<9> > or_ln224_fu_546_p2;
    sc_signal< sc_lv<10> > zext_ln224_fu_558_p1;
    sc_signal< sc_lv<10> > zext_ln224_2_fu_562_p1;
    sc_signal< sc_lv<1> > icmp_ln224_fu_552_p2;
    sc_signal< sc_lv<10> > sub_ln224_fu_575_p2;
    sc_signal< sc_lv<10> > sub_ln224_1_fu_587_p2;
    sc_signal< sc_lv<512> > tmp_3_fu_566_p4;
    sc_signal< sc_lv<10> > xor_ln224_fu_581_p2;
    sc_signal< sc_lv<10> > select_ln224_fu_593_p3;
    sc_signal< sc_lv<10> > select_ln224_2_fu_608_p3;
    sc_signal< sc_lv<10> > sub_ln224_2_fu_616_p2;
    sc_signal< sc_lv<512> > select_ln224_1_fu_601_p3;
    sc_signal< sc_lv<512> > zext_ln224_3_fu_622_p1;
    sc_signal< sc_lv<512> > zext_ln224_4_fu_626_p1;
    sc_signal< sc_lv<512> > lshr_ln224_fu_630_p2;
    sc_signal< sc_lv<512> > lshr_ln224_1_fu_636_p2;
    sc_signal< sc_lv<512> > p_Result_s_fu_642_p2;
    sc_signal< sc_lv<3> > trunc_ln238_fu_670_p1;
    sc_signal< sc_lv<3> > xor_ln238_fu_674_p2;
    sc_signal< sc_lv<11> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<11> ap_ST_fsm_state1;
    static const sc_lv<11> ap_ST_fsm_state2;
    static const sc_lv<11> ap_ST_fsm_state3;
    static const sc_lv<11> ap_ST_fsm_state4;
    static const sc_lv<11> ap_ST_fsm_state5;
    static const sc_lv<11> ap_ST_fsm_state6;
    static const sc_lv<11> ap_ST_fsm_state7;
    static const sc_lv<11> ap_ST_fsm_state8;
    static const sc_lv<11> ap_ST_fsm_state9;
    static const sc_lv<11> ap_ST_fsm_state10;
    static const sc_lv<11> ap_ST_fsm_state11;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<512> ap_const_lv512_lc_1;
    static const sc_lv<6> ap_const_lv6_0;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<64> ap_const_lv64_0;
    static const sc_lv<64> ap_const_lv64_1;
    static const sc_lv<64> ap_const_lv64_2;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<64> ap_const_lv64_3;
    static const sc_lv<64> ap_const_lv64_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<64> ap_const_lv64_5;
    static const sc_lv<64> ap_const_lv64_6;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<64> ap_const_lv64_7;
    static const sc_lv<32> ap_const_lv32_7380166F;
    static const sc_lv<32> ap_const_lv32_4914B2B9;
    static const sc_lv<32> ap_const_lv32_172442D7;
    static const sc_lv<32> ap_const_lv32_DA8A0600;
    static const sc_lv<32> ap_const_lv32_A96F30BC;
    static const sc_lv<32> ap_const_lv32_163138AA;
    static const sc_lv<32> ap_const_lv32_E38DEE4D;
    static const sc_lv<32> ap_const_lv32_B0FB0E4E;
    static const sc_lv<6> ap_const_lv6_20;
    static const sc_lv<6> ap_const_lv6_1;
    static const sc_lv<10> ap_const_lv10_200;
    static const sc_lv<9> ap_const_lv9_1FF;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<8> ap_const_lv8_7;
    static const sc_lv<10> ap_const_lv10_1FF;
    static const sc_lv<32> ap_const_lv32_1FF;
    static const sc_lv<512> ap_const_lv512_lc_2;
    static const sc_lv<5> ap_const_lv5_10;
    static const sc_lv<5> ap_const_lv5_1;
    static const sc_lv<9> ap_const_lv9_1F;
    static const sc_lv<4> ap_const_lv4_8;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<3> ap_const_lv3_7;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_and_ln212_1_fu_504_p2();
    void thread_and_ln212_2_fu_510_p2();
    void thread_and_ln212_fu_492_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_digest_address0();
    void thread_digest_ce0();
    void thread_digest_d0();
    void thread_digest_we0();
    void thread_grp_processmessageblock_fu_297_ap_start();
    void thread_i_6_fu_528_p2();
    void thread_i_7_fu_664_p2();
    void thread_i_fu_309_p2();
    void thread_icmp_ln210_fu_303_p2();
    void thread_icmp_ln212_fu_390_p2();
    void thread_icmp_ln222_fu_522_p2();
    void thread_icmp_ln224_fu_552_p2();
    void thread_icmp_ln236_fu_658_p2();
    void thread_intermediateHash_address0();
    void thread_intermediateHash_address1();
    void thread_intermediateHash_ce0();
    void thread_intermediateHash_ce1();
    void thread_intermediateHash_d0();
    void thread_intermediateHash_d1();
    void thread_intermediateHash_we0();
    void thread_intermediateHash_we1();
    void thread_lshr_ln212_fu_486_p2();
    void thread_lshr_ln224_1_fu_636_p2();
    void thread_lshr_ln224_fu_630_p2();
    void thread_messageBlock_address0();
    void thread_messageBlock_ce0();
    void thread_messageBlock_d0();
    void thread_messageBlock_we0();
    void thread_message_address0();
    void thread_message_ce0();
    void thread_or_ln212_fu_384_p2();
    void thread_or_ln224_fu_546_p2();
    void thread_p_Result_1_fu_516_p2();
    void thread_p_Result_2_fu_356_p4();
    void thread_p_Result_3_fu_366_p5();
    void thread_p_Result_s_fu_642_p2();
    void thread_pack_fu_340_p2();
    void thread_select_ln212_1_fu_422_p3();
    void thread_select_ln212_2_fu_430_p3();
    void thread_select_ln212_3_fu_472_p3();
    void thread_select_ln212_fu_414_p3();
    void thread_select_ln224_1_fu_601_p3();
    void thread_select_ln224_2_fu_608_p3();
    void thread_select_ln224_fu_593_p3();
    void thread_shl_ln1_fu_538_p3();
    void thread_shl_ln212_1_fu_480_p2();
    void thread_shl_ln212_fu_456_p2();
    void thread_shl_ln_fu_377_p3();
    void thread_sub_ln216_fu_330_p2();
    void thread_sub_ln224_1_fu_587_p2();
    void thread_sub_ln224_2_fu_616_p2();
    void thread_sub_ln224_fu_575_p2();
    void thread_tmp_3_fu_566_p4();
    void thread_tmp_fu_462_p4();
    void thread_trunc_ln212_fu_320_p1();
    void thread_trunc_ln224_fu_534_p1();
    void thread_trunc_ln238_fu_670_p1();
    void thread_xor_ln212_1_fu_438_p2();
    void thread_xor_ln212_2_fu_498_p2();
    void thread_xor_ln212_fu_408_p2();
    void thread_xor_ln218_fu_346_p2();
    void thread_xor_ln224_fu_581_p2();
    void thread_xor_ln238_fu_674_p2();
    void thread_zext_ln212_1_fu_396_p1();
    void thread_zext_ln212_2_fu_400_p1();
    void thread_zext_ln212_3_fu_404_p1();
    void thread_zext_ln212_4_fu_444_p1();
    void thread_zext_ln212_5_fu_448_p1();
    void thread_zext_ln212_6_fu_452_p1();
    void thread_zext_ln212_fu_315_p1();
    void thread_zext_ln216_1_fu_336_p1();
    void thread_zext_ln216_2_fu_327_p1();
    void thread_zext_ln216_fu_324_p1();
    void thread_zext_ln218_fu_352_p1();
    void thread_zext_ln224_1_fu_653_p1();
    void thread_zext_ln224_2_fu_562_p1();
    void thread_zext_ln224_3_fu_622_p1();
    void thread_zext_ln224_4_fu_626_p1();
    void thread_zext_ln224_fu_558_p1();
    void thread_zext_ln238_1_fu_685_p1();
    void thread_zext_ln238_fu_680_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
